### ISSUE TITLE
Autosplitter inaccurate, 

### ISSUE THREAD

**Issue by Retartist** [partoftheworlD/MyFriendPedro_autosplitter#4]
![image](https://user-images.githubusercontent.com/49677613/121502204-4aa62280-ca23-11eb-99d2-3f86f6964f10.png)
Splitter is quite a bit faster than ingame time (almost 1 min vs mfp over the whole of old town)

**Comment by partoftheworlD** [comment]
Is there a video? I would like to see at what point the deletion of time occurred.

**Comment by Retartist** [comment]
Here is a video freshly made (Still processing on YT at the time of this message), You can see the time difference by the end of the first level and it goes to over a minute by the end of it. 
https://youtu.be/WCeuOYLhz7M

**Comment by partoftheworlD** [comment]
Oh, it's ok. Because igt timer counts black screen time after level is loaded, while the autosplitter only counts gameplay time, from first possible input, to last

**Comment by Retartist** [comment]
That doesn't seem correct or account for the time, if you look at 11 seconds in (well into gameplay on the boxes), IGT is 3.58 and livesplit is 3.25 (0.33sec diff). Compare that to the end of the level, IGT is 54.17 and livesplit is 49.9 (4.27 sec difference!). 

Where did the 3.94 seconds come from during the level?

**Comment by partoftheworlD** [comment]
> That doesn't seem correct or account for the time, if you look at 11 seconds in (well into gameplay on the boxes), IGT is 3.58 and livesplit is 3.25 (0.33sec diff). Compare that to the end of the level, IGT is 54.17 and livesplit is 49.9 (4.27 sec difference!).
> 
> Where did the 3.94 seconds come from during the level?

Thanks for the report, I found the problem, but I can't solve it because the problem is related to CPU scheduler and game optimization. More details on the discord server.
